# Generated by Django 4.1.3 on 2022-12-07 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_first_name', models.CharField(max_length=20)),
                ('emp_last_name', models.CharField(max_length=20)),
                ('emp_pay', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game_studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_games_released', models.IntegerField()),
                ('studio_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=20)),
                ('g_qty_sold', models.IntegerField()),
                ('gs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game_studio')),
            ],
        ),
        migrations.CreateModel(
            name='IAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iap_name', models.CharField(max_length=20)),
                ('iap_cost', models.IntegerField()),
                ('g_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.games')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('g_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.games')),
                ('iap_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.iap')),
            ],
        ),
    ]
