# Generated by Django 4.1.3 on 2022-12-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_game_studio_games_iap_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Games', models.CharField(blank=True, choices=[[1, 'Gta 5']], max_length=20)),
            ],
        ),
    ]
