# Generated by Django 4.1.3 on 2022-12-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_game_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
