# Generated by Django 4.1.3 on 2022-12-08 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customer_password_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='g_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.games'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='iap_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.iap'),
        ),
    ]
