# Generated by Django 4.1.3 on 2022-12-08 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_transaction_g_id_alter_transaction_iap_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_info',
            name='Games',
            field=models.CharField(blank=True, choices=[[1, 'Gta V'], [2, 'Gta IV']], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='g_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.games'),
        ),
    ]
